import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,readFileSync,statSync,writeFileSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {EcosystemService} from '../src/ecosystem.js';
import type {CouncilDecision,CouncilInput} from '../src/ecosystem-types.js';
const decision:CouncilDecision={title:'Start free',summary:'Preserve savings',conflicts:[{topic:'Cost',positions:'Health wants a gym; Finance protects savings.',resolution:'Try home training first.'}],alternatives:[{title:'Home workout',estimatedCost:0,cadence:'monthly',rationale:'No membership required.',sourceIds:[]}],recommendation:'Try free home exercise for two weeks.',cautions:['Prices and availability need confirmation.']};
function fixture(t:{after:(fn:()=>void)=>void},opts:ConstructorParameters<typeof EcosystemService>[0]={}){const dir=mkdtempSync(join(tmpdir(),'ecosystem-test-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const statePath=join(dir,'state.json');return{statePath,service:new EcosystemService({statePath,providerStatus:()=>({agents:true,voice:true,search:true}),council:async()=>decision,...opts})};}
test('custom domains persist, are editable, and have validated tool and color values',t=>{const{service,statePath}=fixture(t);const template=service.getState().mentors[0]!;const input={...template,id:'',name:'Roam',domain:'Slow travel',goals:['Accessible holidays'],color:'#7366DD'};const saved=service.saveMentor(input);assert.equal(saved.mentors.length,4);const custom=saved.mentors.at(-1)!;assert.notEqual(custom.id,'');service.saveMentor({...custom,name:'Roam Plus'});assert.equal(service.getState().mentors.at(-1)!.name,'Roam Plus');assert.throws(()=>service.saveMentor({...custom,tools:['shell']}));assert.throws(()=>service.saveMentor({...custom,color:'red;url(bad)'}));assert.equal(statSync(statePath).mode&0o777,0o600);const restarted=new EcosystemService({statePath});assert.equal(restarted.getState().mentors.at(-1)!.domain,'Slow travel');service.deleteMentor(custom.id);assert.equal(service.getState().mentors.length,3);});
test('council gets shared profile and prior approved memory; approval is exact and idempotent',async t=>{let captured:CouncilInput|undefined;const{service}=fixture(t,{council:async(input,hooks)=>{captured=input;hooks.message({id:'msg',mentorId:'finance',mentorName:'Penny',to:'Mira',phase:'review',text:'Protect savings.',at:new Date().toISOString()});return decision;}});const result=await service.council({prompt:'Should I buy this membership?',mentorIds:['health','finance']});assert.equal(result.run!.status,'pending');assert.equal(result.memory.length,0);assert.equal(captured!.profile.wellnessBudget,250);assert.equal(result.run!.messages[0]!.to,'Mira');assert.throws(()=>service.decide('wrong','approve'));service.decide(result.run!.id,'approve');service.decide(result.run!.id,'approve');assert.equal(service.getState().memory.length,1);await service.council({prompt:'What about next month?',mentorIds:['health','finance']});assert.equal(captured!.memory.length,1);});
test('profile or mentor changes invalidate a pending decision; rejected suggestions are not memory',async t=>{const{service}=fixture(t);let r=await service.council({prompt:'Review my fitness spending',mentorIds:['health','finance']});service.saveProfile({...r.profile,monthlyIncome:0});assert.equal(service.getState().run!.status,'failed');assert.throws(()=>service.decide(r.run!.id,'approve'));r=await service.council({prompt:'Review my fitness spending',mentorIds:['health','finance']});service.decide(r.run!.id,'reject');assert.equal(service.getState().memory.length,0);assert.throws(()=>service.decide(r.run!.id,'approve'));});
test('active review cannot be duplicated or have its context changed',async t=>{let finish!:(value:CouncilDecision)=>void;const{service}=fixture(t,{council:()=>new Promise(r=>{finish=r;})});const run=service.council({prompt:'Review my fitness spending',mentorIds:['health','finance']});await assert.rejects(service.council({prompt:'Another review',mentorIds:['health','finance']}),/running/);assert.throws(()=>service.saveProfile(service.getState().profile),/running/);assert.throws(()=>service.deleteMentor('career'),/running/);finish(decision);await run;});
test('failed or interrupted runs never gain approval; saved failure survives restart',async t=>{const{service,statePath}=fixture(t,{council:async()=>{throw new Error('Synthetic provider outage');}});await assert.rejects(service.council({prompt:'Review gym spending',mentorIds:['health','finance']}),/outage/);assert.equal(service.getState().run!.status,'failed');assert.throws(()=>service.decide(service.getState().run!.id,'approve'));const value=JSON.parse(readFileSync(statePath,'utf8'));value.run.status='running';writeFileSync(statePath,JSON.stringify(value));const recovered=new EcosystemService({statePath});assert.equal(recovered.getState().run!.status,'failed');assert.match(recovered.getState().run!.error!,/interrupted/);});
test('missing and duplicate mentors, malformed profile and unknown fields are rejected before model calls',async t=>{const{service}=fixture(t);await assert.rejects(service.council({prompt:'Review gym spending',mentorIds:['health','health']}),/once/);await assert.rejects(service.council({prompt:'Review gym spending',mentorIds:['health','missing']}),/no longer/);assert.throws(()=>service.saveProfile({...service.getState().profile,monthlyIncome:NaN}));assert.throws(()=>service.saveProfile({...service.getState().profile,apiKey:'secret'}));assert.equal(service.getState().run,null);});
